sagemath/cypari2

cypari2/closure.pyx
cypari2/convert.pyx
cypari2/gen.pyx
cypari2/handle_error.pyx
cypari2/pari_instance.pyx
cypari2/stack.pyx
setup.py

As a consequence, `cypari2` now builds without warnings, except for some `-Wmaybe-uninitialized` false positives.

cysignals: cimports instead of deprecated .pxi files

---

cypari2/string_utils.pyx

The old pre-Python-3 version of `cypari2` actually did a conversion `str(s)` if needed. The new version requires that `s` is already a `bytes` or `unicode` object. This causes several regressions in SageMath.

to_bytes and to_unicode: convert if needed

---

.travis.yml
autogen/doc.py
autogen/generator.py
autogen/parser.py
autogen/paths.py
tests/rundoctest.py

Converted autogen doctests to Python syntax

---

.travis-install-pari.sh
.travis.yml
cypari2/gen.pyx

We should test:
- PARI 2.8.1 (the oldest version supported)
- PARI 2.9.3 (latest stable)
- PARI master

Test multiple PARI versions

---

cypari2/pari_instance.pyx

These three doctests fail on Cygwin, because the actual size for vsize depends on `PARI_STACK_ALIGNMENT` which in turn depends on `sysconf(_SC_PAGESIZE)` which is different on Cygwin than on Linux, for example.
This fix is just a hack though.  It might be better API-wise if `Pari.allocatemem` just returned the set stack size/maxsize as a tuple, and didn't print anything (better left up to the application).  The doctest could make a more precise comparison if desired.

Fix failing tests on Cygwin

---

autogen/args.py
autogen/generator.py
autogen/parser.py
autogen/paths.py
autogen/ret.py

As suggested by @embray, do the auto-generation of the code the "Python 3" way, using Unicode everywhere.

Use Unicode everywhere for autogenerating code

---

autogen/__init__.py
autogen/parser.py
autogen/paths.py

Always use `str` instead of `bytes` for filenames.
@embray

Convert pari_share() to str

---

cypari2/gen.pyx

- make access to bnf members `fu` and `tu` via `bnf_get_fu` and `bnf_gt_fu`.
- deprecate `bnfunit`

bnf_get_fu and bnf_get_tu

---

autogen/paths.py

Needed to cross compile for macos-arm64 from macos-x86_64

Use PARI_SHARE env variable to support cross compiling

---

.github/workflows/main.yml
.travis-install-pari.sh

As Travis-CI isn't working currently, we should have some other way to test how things are working out.

GitHub workflow

---

.github/workflows/main.yml
cypari2/Py_SET_SIZE.h
cypari2/convert.pxd
cypari2/convert.pyx
setup.py

This shall fix #114.
It is supposed to replace:
- #115, as it also provided the CI tests for python 3.11
- #103 (which is included, but fixed in terms of depending only on cython 0.29).

fix for python 3.11

---

.github/workflows/main.yml
Makefile
README.rst
_custom_build_meta.py
cypari2/gen.pyx
docs/source/conf.py
pyproject.toml
setup.py

This PR started out with minimal changes, replacing the outdated use of `setup_requires`.
Fixes #93 
(with a cleaner solution for augmenting the build-time path than the stalled PR #104).

Add pyproject.toml, update installation instructions for modern Python packaging, fix docbuild, update CI scripts, add Cython 3 support

---

.github/workflows/main.yml
MANIFEST.in

We use the reusable workflows from Sage to test portability and integration with Sage.

.github/workflows/main.yml: Add portability/integration testing with Sage

---

.github/workflows/main.yml
autogen/paths.py
cypari2/Py_SET_SIZE.h
cypari2/convert.pyx
cypari2/pycore_long.h
cypari2/pycore_long.pxd

The necessary functions are copied from cpython 3.12 `Include/internal/pycore_long.h`, which is private. This should make it easy to copy new versions if cpython internals change. For cpython < 3.12 I implemented equivalent functions.
All of this is placed in separate files `pycore_long.pxd` and `pycore_long.h` so it's easy to share between projects (fpylll, sagemath).
Tested in 64-bit and 32-bit x86.
Fixes: #137

Support python 3.12

---

cypari2/pycore_long.h

This was introduced by accident in #138.
The typo leads to errors like below, when trying to build for Python <= 3.8:
```C
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DOPENSSL_NO_SSL3 -fPIC -Icypari2 -I/tmp/virt/lib/python3.8/site-packages/cysignals -I/usr/include -I/tmp/virt/include -I/home/jjan/.pyenv/versions/3.8.18/include/python3.8 -c cypari2/convert.c -o build/temp.linux-x86_64-3.8/cypari2/convert.o
In file included from /home/jjan/.pyenv/versions/3.8.18/include/python3.8/pytime.h:6,
from /home/jjan/.pyenv/versions/3.8.18/include/python3.8/Python.h:85,
from cypari2/convert.c:49:
cypari2/pycore_long.h: In function ‘_PyLong_SetSignAndDigitCount’:
cypari2/pycore_long.h:92:13: error: ‘o’ undeclared (first use in this function); did you mean ‘op’?
92 | …
```

Fix typo for Python <= 3.8.

---

cypari2/convert.pyx

fix cython-lint in convert.pyx

---

cypari2/gen.pyx

add one check for matrix index

---

cypari2/handle_error.pyx
cypari2/pari_instance.pyx
cypari2/paridecl.pxd
cypari2/types.pxd

more insignificant little details fixed

fixng some cython-lint suggestions

---

.github/workflows/main.yml
cypari2/stack.pyx

drop macos 13 failing check

---

pyproject.toml
setup.py

Modernize project metadata by moving it from setup.py to pyproject.toml

Modernize project metadata

---

cypari2/closure.pyx
cypari2/convert.pxd
cypari2/convert.pyx
cypari2/gen.pxd
cypari2/gen.pyx
cypari2/handle_error.pxd
cypari2/handle_error.pyx
cypari2/pari_instance.pxd
cypari2/pari_instance.pyx
cypari2/paridecl.pxd
cypari2/stack.pxd
cypari2/stack.pyx

- **fix implicit noexcept warnings**
- **fix type to avoid size_t -> python -> size_t conversion**

Add missing noexcept clauses

---

.github/workflows/main.yml

that have not reached their end of life, see https://endoflife.date/python

Test with all supported versions of Python

---

.github/workflows/main.yml
README.rst
pyproject.toml

build with Python 3.8 seems to fail with
```
In file included from /home/conda/feedstock_root/build_artifacts/cypari2_1705557903378/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/python3.8/pytime.h:6,
from /home/conda/feedstock_root/build_artifacts/cypari2_1705557903378/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include/python3.8/Python.h:85,
from cypari2/convert.c:50:
cypari2/pycore_long.h: In function '_PyLong_SetSignAndDigitCount':
cypari2/pycore_long.h:92:13: error: 'o' undeclared (first …
```

Require Python 3.9

---

.github/workflows/wheels.yml
pyproject.toml

We add a GH Actions workflow that builds sdists and wheels for PyPI.
Wheel-building uses the Sage distribution to build the prerequisites from scratch.
This can later be refactored using a reusable workflow - https://github.com/sagemath/sage/pull/36525
Resolves #105.

.github/workflows/wheels.yml: New

---

README.rst
cypari2/closure.pyx
cypari2/convert.pyx
cypari2/gen.pxd
cypari2/gen.pyx
cypari2/handle_error.pyx
cypari2/pari_instance.pyx
cypari2/stack.pyx
pyproject.toml
setup.py

WIP waiting for a Cython 3.0 release.
Also other changes that require Cython 3.0.

Use the trashcan for class Gen (needs Cython 3)

---

.github/workflows/main.yml
NEWS
cypari2/__init__.py
cypari2/custom_block.pyx
pyproject.toml

This is a revival of #117 that has wrongly been merged into master. Before this gets merged, cysignals has to be released.

Cysignals hook

---

cypari2/paridecl.pxd
cypari2/types.pxd

Needed to port sagemath to work with pari 2.17

Add pari_PRIMES declaration

---

autogen/generator.py

as this is giving warnings when using cython-lint
also some pep8 formatting of the modified file

get rid of trailing whitespace in autogenerated files

---

.github/workflows/dist.yml
.github/workflows/main.yml
.install-pari.sh

update un/download artefacts action to v4

---

cypari2/convert.pxd

see #169
not sure if this is correct. One could maybe remove the conversion ?

PyLong_AsLong in convert.pxd

---

autogen/ret.py

instead of #134, just use the important commit. This will fix #133

fix m prototype
